import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainNav from "./components/mainNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fullstack StigoRX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="main-header">
          <MainNav />
        </header>
        <main className="bg-slate-300 text-black main-content">{children}</main>
        <footer>
          <h2>this is the app footer</h2>
        </footer>
      </body>
    </html>
  );
}
